#!/usr/bin/env ruby
#
require 'rubygems'
require 'csv'

gems = []

File.open('data/Marshal.4.8.Z', 'r:utf-8') do |file|
  gems = Marshal.load Gem.inflate(file.read)
end

pipe = '|'

CSV.open('data/gems.csv', 'wb') do |file|
  i = 0
  
  last_name         = nil
  last_versions     = []
  last_authors      = []
  last_dependencies = nil
  last_summary      = nil
  
  gems.inject do |last_name, name_and_spec|
    name, spec = name_and_spec
    name = name[/(.+?)-\d+\./, 1]
    
    # Inject until the name changes (they are sorted alphabetically)
    #
    if last_name == name
      # do not write, but remember some values.
      #
      last_dependencies = spec.dependencies
      last_authors      = (spec.authors || []) << spec.author
      last_versions     << spec.version
      last_summary      = spec.summary unless spec.summary.empty?
    else
      i += 1
      versions     = last_versions.join pipe
      authors      = last_authors.uniq.compact.join pipe
      dependencies = last_dependencies && last_dependencies.map { |dependency| dependency.name }.join(pipe) || ""
      
      # Write to file.
      #
      file << [i, last_name, versions, authors, dependencies, last_summary]
      
      # reset things
      #
      last_name         = name
      last_dependencies = nil
      last_authors      = []
      last_versions     = []
      last_summary      = nil
    end
    name
  end
end